# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c96d9005b389c93cb27b341977536ee69b6a964a18f24ea7440003b9a02a3a22fafad649ee7917870705a0480ded5d67e3504827b3cb24061901e20271f9ca96

test:
  secret_key_base: c98696d6f8139ec53a0f07ce7f7fbbe2ae9c026a35149eeb8fbe7520fc45599dc4dc91f74572ff41a9c9a1e68921929877fabc24f2926ee57af37220742762a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
